### ISSUE TITLE
Plugin causes Android Studio to crash when a DATETIME column is used

### ISSUE THREAD

**Issue by frankvollebregt** [NicolaVerbeeck/local_storage_inspector_plugin#1]
From what I can tell, it doesn't matter whether it's a DateTime stored as an `INT` or a `TEXT` (according to the [store_date_time_values_as_text](https://drift.simonbinder.eu/docs/advanced-features/builder_options/) setting in the build options).

It also doesn't matter whether there is any data in the table at the time of loading, so I guess it has to do with setting up the table/columns.

https://drift.simonbinder.eu/docs/using-sql/drift_files/#supported-column-types

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')
	at com.chimerapps.storageinspector.ui.ide.view.sql.TableViewColumnInfo.valueOf(CustomDataTableView.kt:294)
	at com.chimerapps.storageinspector.ui.ide.view.sql.TableViewColumnInfo.valueOf(CustomDataTableView.kt:271)
	at com.intellij.util.ui.ListTableModel.getValueAt(ListTableModel.java:97)
	at java.desktop/javax.swing.JTable.getValueAt(JTable.java:2764)
	at java.desktop/javax.swing.JTable.prepareRenderer(JTable.java:5795)
	at com.intellij.ui.table.JBTable.prepareRenderer(JBTable.java:700)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2210)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2112)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1908)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:845)
	at com.intellij.ui.table.JBTable.paintComponent(JBTable.java:417)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1115)
	at com.intellij.ui.table.JBTable.paint(JBTable.java:547)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:736)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:235)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5312)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1668)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1643)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1580)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1347)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5260)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5070)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:882)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:838)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:787)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1909)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:786)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:737)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:488)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by NicolaVerbeeck** [comment]
Let me take a look, I am not doing much (any) mobile development anymore so I need to dust up the plugin with the latest changes.

Did you verify that this also happens when the `store_date_time_values_as_text` is false?

**Comment by frankvollebregt** [comment]
Thanks for still looking into this, despite not using it yourself anymore :) 

I had a look at the source code and based on that I'd think this only occurs when that build setting is enabled, but while testing for this issue, I thought I also encountered it with the setting disabled. In hindsight, this may also have been because I didn't correctly migrate the columns.

I'll have another try and let you know.

**Comment by NicolaVerbeeck** [comment]
I uploaded a new version 0.5.0 which may or may not fix this issue. It is under review by jetbrains

**Comment by frankvollebregt** [comment]
Awesome, I'll try it out when it becomes available and let you know if it works as expected

**Comment by frankvollebregt** [comment]
I just tried it out, and it looks like it fails to parse the DateTime in the database as a Java DateTime:
```
java.time.format.DateTimeParseException: Text '2018-10-30T06:52:00' could not be parsed at index 19
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2052)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1954)
	at java.base/java.time.OffsetDateTime.parse(OffsetDateTime.java:404)
	at java.base/java.time.OffsetDateTime.parse(OffsetDateTime.java:389)
	at com.chimerapps.storageinspector.ui.ide.view.sql.TableViewColumnInfo.parseDateTime(CustomDataTableView.kt:341)
	at com.chimerapps.storageinspector.ui.ide.view.sql.TableViewColumnInfo.valueOf(CustomDataTableView.kt:327)
	at com.chimerapps.storageinspector.ui.ide.view.sql.TableViewColumnInfo.valueOf(CustomDataTableView.kt:298)
	at com.intellij.util.ui.ListTableModel.getValueAt(ListTableModel.java:97)
	at java.desktop/javax.swing.JTable.getValueAt(JTable.java:2764)
	at java.desktop/javax.swing.JTable.prepareRenderer(JTable.java:5795)
	at com.intellij.ui.table.JBTable.prepareRenderer(JBTable.java:700)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2210)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2112)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1908)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:845)
	at com.intellij.ui.table.JBTable.paintComponent(JBTable.java:417)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1115)
	at com.intellij.ui.table.JBTable.paint(JBTable.java:547)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:736)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:235)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5312)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1668)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1643)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1580)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1347)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5260)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5070)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:882)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:838)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:787)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1909)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:786)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:737)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:488)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```
Index 19 is out of bounds, so I guess it always expects to find a dot, milliseconds or a Z, whereas SQLite (through Drift) does not

**Comment by NicolaVerbeeck** [comment]
Seems like I have to put in some more effort than I hoped. It will be a little while before I can take this up due to other workload. 

If you are in need of this feel free to create a PR

**Comment by frankvollebregt** [comment]
No problem at all! I'll have a look.

It works fine for actual full ISO strings, though!
![image](https://github.com/NicolaVerbeeck/local_storage_inspector_plugin/assets/23523399/a9217d90-727d-4e5a-bb41-618f9b045a7a)

Thanks for still finding some time to get this patch ready this quickly :)

**Comment by frankvollebregt** [comment]
It looks like simply appending a `Z` to a timestamp without a Z or explicit timezone will prevent this exception. I made a PR to your feature branch, so if you have some time feel free to take a look.

### These can be parsed
```
- 2023-10-03T12:00:00.000Z
- 2023-10-03T12:00Z
- 2023-10-03T12:00:00.000+00:00
- 2023-10-03T12:00+12:34
- 2023-10-03T12:00:00.000+01
```
### Whereas these cannot
```
- 2023-10-03T12:00:00.000
- 2023-10-03T12:00:00.000+0
- 2023-10-03T12:00
```

I added a simple regex that checks whether or not the `raw` string ends with a `Z` or `+dd:dd` (where `d` denotes a digit). If it does not, I append a `Z` and parse the results.

Of course this may still throw an exception if some value in the database is not a valid ISO string. I am hesitant to add a default value like `0` as the `long` result, though that would prevent the issue. Any thoughts on this last point?

**Comment by frankvollebregt** [comment]
@NicolaVerbeeck I guess there needs to be a version bump before pushing it to Jetbrains? Let me know when it's up (or if something else still needs to be done)

Thanks!

**Comment by NicolaVerbeeck** [comment]
It is unfortunately still a manual process so I need to find some time to switch to my mac and do it. Probably tomorrow if that is ok

**Comment by frankvollebregt** [comment]
Of course, no problem. I'll probably use the manual `runIde` version in the meantime :)

**Comment by NicolaVerbeeck** [comment]
I think there should be a gradle option to build the plugin and then use install from disk with that zip file :)

**Comment by frankvollebregt** [comment]
🤦 of course there is that option, I somehow didn't even think to check. Thanks, I've loaded it into Android Studio and it works perfectly :D

**Comment by NicolaVerbeeck** [comment]
Release 0.5.1 was pushed to jetbrains for review. Thanks @frankvollebregt !
